name: run the_morning.py

on:
  [push]
  # schedule:
  #   - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      
      - name: i use selenium chromedriver so i need to download this
        uses: nanasess/setup-chromedriver@v1

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: execute py script # run main.py
        env:
          WEBHOOKS: ${{ secrets.WEBHOOKS }}
        run: python the_morning.py
